2022-05-24 16:59:16,293 INFO: Microblog startup [in D:\python\МегаУчебник\microblog\app\__init__.py:40]
2022-05-30 15:06:13,217 INFO: Microblog startup [in D:\python\МегаУчебник\microblog\app\__init__.py:40]
2022-05-30 15:06:35,519 ERROR: Exception on /edit_profile [GET] [in D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\python\МегаУчебник\microblog\app\routes.py", line 82, in edit_profile
    form= EditProfileForm(current_user.username)
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "D:\python\МегаУчебник\microblog\app\forms.py", line 36, in __init__
    super(EditPrifileForm, self).__init__(*args, **kwargs)
NameError: name 'EditPrifileForm' is not defined
2022-05-30 15:06:52,038 ERROR: Exception on /edit_profile [GET] [in D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\python\МегаУчебник\microblog\app\routes.py", line 82, in edit_profile
    form= EditProfileForm(current_user.username)
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "D:\python\МегаУчебник\microblog\app\forms.py", line 36, in __init__
    super(EditPrifileForm, self).__init__(*args, **kwargs)
NameError: name 'EditPrifileForm' is not defined
2022-05-30 15:07:21,617 ERROR: Exception on /edit_profile [GET] [in D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\python\МегаУчебник\microblog\app\routes.py", line 82, in edit_profile
    form= EditProfileForm(current_user.username)
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "D:\python\МегаУчебник\microblog\app\forms.py", line 36, in __init__
    super(EditPrifileForm, self).__init__(*args, **kwargs)
NameError: name 'EditPrifileForm' is not defined
2022-05-30 15:07:41,675 ERROR: Exception on /edit_profile [GET] [in D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\python\МегаУчебник\microblog\app\routes.py", line 82, in edit_profile
    form= EditProfileForm(current_user.username)
  File "D:\python\МегаУчебник\microblog\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "D:\python\МегаУчебник\microblog\app\forms.py", line 36, in __init__
    super(EditPrifileForm, self).__init__(*args, **kwargs)
NameError: name 'EditPrifileForm' is not defined
2022-05-30 15:09:05,297 INFO: Microblog startup [in D:\python\МегаУчебник\microblog\app\__init__.py:40]
